# Spring Application Configuration
spring.application.name=quantity-measurement-app

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:quantity_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console Settings
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# JPA/Hibernate Settings
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Actuator Monitoring Configurations
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# Swagger Springdoc OpenAPI Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Security configurations
spring.security.user.name=user
spring.security.user.password=password

# Logging Configurations
logging.level.com.app.quantitymeasurement=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=INFO
